name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.15.x"]
    runs-on: "ubuntu-20.04"
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
    - name: Check style
      run: |
        gofmt -w -s .
        git diff --exit-code
    - name: Test
      run: |
        go vet ./...
        go test -v ./...
